server:
  port: 8080

spring:
  mail:
    default-encoding: UTF-8

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/graduation_design?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #Spring Boot \u9ED8\u8BA4\u662F\u4E0D\u6CE8\u5165\u8FD9\u4E9B\u5C5E\u6027\u503C\u7684\uFF0C\u9700\u8981\u81EA\u5DF1\u7ED1\u5B9A
    #druid \u6570\u636E\u6E90\u4E13\u6709\u914D\u7F6E
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #\u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1\u62E6\u622A\u7684filters\uFF0Cstat\uFF1A\u76D1\u63A7\u7EDF\u8BA1\u3001log4j\uFF1A\u65E5\u5FD7\u8BB0\u5F55\u3001wall\uFF1A\u9632\u5FA1sql\u6CE8\u5165
      #\u5982\u679C\u5141\u8BB8\u62A5\u9519\uFF0Cjava.lang.ClassNotFoundException: org.apache.Log4j.Properity
      #\u5219\u5BFC\u5165log4j \u4F9D\u8D56\u5C31\u884C
      filters: stat,wall
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  thymeleaf:
    cache: false
    prefix: classpath:static/
    suffix: .html
    enabled: true
    encoding: UTF-8
    mode: HTML



# \u6574\u5408mybatis
mybatis:
  type-aliases-package: com.lwl.pojo
  mapper-locations: classpath:mapper/*.xml

